default: &default

  adapter: postgresql

  encoding: unicode

  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

  port: 5432

  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>

  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  timeout: 5000



development:

  <<: *default

  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT") { "movie_explorer_api_development" } %>


test:

  <<: *default

  database: <%= ENV.fetch("DB_NAME_TEST") { "movie_explorer_api_test" } %>


production:

  url: <%= ENV['DATABASE_URL'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>